valor = input('Digite algo:  ')
print(f'O tipo primitivo de {valor} é {type(valor)}')
print(f'{valor} é alfanumérico? {valor.isalnum()}')
print(f'{valor} é numérico? {valor.isnumeric()}')
print(f'{valor} é espaço? {valor.isspace()}')
print(f'{valor} é tudo maiúsculo? {valor.isupper()}')
print(f'{valor} é tudo minúsculo? {valor.islower()}')
print(f'{valor} é printável? {valor.isprintable()}')
print(f'{valor} esta capitalizado? {valor.istitle()}')
