from time import sleep
pessoa = str(input('Digite seu nome completo:  ')).strip().title()
print('Analizando seu nome...')
sleep(5)
print(f'O nome digitado foi: {pessoa}')
sleep(5)
print(f'O nome todo escrito em letras maiúsculas fica assim: {pessoa.upper()}')
sleep(5)
print(f'O nome todo escrito em letras minúsculas fica assim: {pessoa.lower()}')
pessoa1 = pessoa.split()
junto = ''.join(pessoa1)
sleep(5)
print(f'O nome {pessoa} tem ao todo {len(junto)} letras')
sleep(5)
print(f'O primeiro nome que é {pessoa1[0]} tem {len(pessoa1[0])} letras')
sleep(5)
print('O nome {} tem ao todo {} letras'.format(pessoa, len(pessoa) - pessoa.count(' ')))
sleep(5)
print('O primeiro nome tem {} letras'.format(pessoa.find(' ')))
sleep(3)
print('Analize de texto finalizada com sucesso!!')
